---
title: "Ex1 - LinkedIn Network"
author: "Jennifer Liu"
date: "2024-03-18"
output:
  html_document:
    df_print: paged
---

```{r}
# Setup chunk for RMarkdown
knitr::opts_chunk$set(echo = TRUE)
# Load necessary packages
library(tidyverse)
library(tidygraph)
library(igraph)
# Load connections data
connections = read.csv("C:/Users/Admin/Downloads/Basic_LinkedInDataExport_03-18-2024/Connections.csv")
```

```{r}
number_of_connections <- connections %>%
  group_by(Company) %>%
  summarise(count = n()) %>%
  arrange(desc(count))

total_num <- nrow(connections)

print(number_of_connections)
print(total_num)

```

```{r}
library(ggraph)

# Process connections for network analysis
connections <- connections %>%
  mutate(contact_id = row_number(),
         label = paste(First.Name, substr(Last.Name, 1, 1), sep = " "))
```

```{r}
nodes <- connections %>%
  select(contact_id, label, Company) %>%
  distinct()

specified_companies <- c("McGill University - Desautels Faculty of Management",
                         "McGill University")
```

```{r}
edges <- connections %>%
  select(contact_id, Company) %>%
  filter(Company %in% specified_companies) %>%
  distinct() %>%
  mutate(from = 0, to = contact_id) %>%
  select(from, to)

my_node <- data.frame(contact_id = 0, label = "Me", Company = NA)
nodes <- bind_rows(my_node, nodes)

```

```{r}
#install.packages("purrr")
library(purrr)
library(dplyr)
library(tidyr)

internal_edges <- connections %>%
  select(contact_id, Company) %>%
  distinct() %>%
  group_by(Company) %>%
  filter(n() > 1 & !Company %in% specified_companies) %>%
  summarise(contact_ids = list(contact_id), .groups = 'drop') %>%
  mutate(pairs = map(contact_ids, ~combn(.x, 2, simplify = FALSE))) %>%
  tidyr::unnest(pairs) %>%
  mutate(from = map_chr(pairs, ~as.character(.x[1])),
         to = map_chr(pairs, ~as.character(.x[2]))) %>%
  select(from, to)

```

```{r}
#install.packages("ggraph")
library(ggraph)
ggraph(network, layout = 'fr') +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = label), repel = TRUE) +
  theme_graph()
```
